# Generated by Django 4.2.3 on 2023-07-21 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father', models.CharField(max_length=50)),
                ('guarantor', models.CharField(max_length=50)),
                ('borrow_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('contact_one', models.CharField(max_length=15)),
                ('contact_two', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('interest', models.DecimalField(decimal_places=1, max_digits=3)),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField()),
                ('identity', models.ImageField(upload_to='./identity')),
            ],
        ),
    ]
