# Generated by Django 4.2.3 on 2023-07-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='contact_guar',
            field=models.CharField(default=9999999999, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entries',
            name='identity',
            field=models.ImageField(upload_to='main/identity'),
        ),
    ]
