# Generated by Django 4.2.3 on 2023-07-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_entries_contact_guar_alter_entries_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='identity',
            field=models.ImageField(upload_to='identities'),
        ),
    ]
