# Generated by Django 4.2.3 on 2023-08-03 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_entries_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='entries',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('pay_type', models.CharField(choices=[('CA', 'Cash'), ('UP', 'UPI'), ('BT', 'Bank Transfer')], max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.entries')),
            ],
        ),
    ]
