# Generated by Django 4.2.3 on 2023-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_entries_interest_alter_entries_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='pay_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Bank Transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
