# Generated by Django 4.2.3 on 2023-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_installment_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='pay_type',
            field=models.CharField(choices=[('CA', 'Cash'), ('GP', 'GPay'), ('PH', 'Phone Pay'), ('PA', 'Paytm'), ('BT', 'Bank Transfer')], max_length=50),
        ),
    ]
