# Generated by Django 4.2.3 on 2023-08-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_installment_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='address',
            field=models.CharField(default='Test address, blabla, 135541', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installment',
            name='pay_type',
            field=models.CharField(choices=[('GP', 'GPay'), ('PH', 'Phone Pay'), ('PA', 'Paytm'), ('CA', 'Cash'), ('BT', 'Bank Transfer')], max_length=50),
        ),
    ]
