# Generated by Django 4.2.3 on 2023-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_entries_address_alter_installment_pay_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='identity',
            field=models.FileField(upload_to='identities'),
        ),
    ]
