# Generated by Django 4.2.3 on 2023-08-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_entries_identity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='amount',
            new_name='principal',
        ),
    ]
