# Generated by Django 4.2.3 on 2023-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_entries_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='due_date',
            field=models.DateField(),
        ),
    ]
